### ISSUE TITLE
Where I can download the char-CNN-RNN-embeddings.pickle?

### ISSUE THREAD

**Issue by hackpython** [jppgks/stackgan-pp#10]
Hi , Thank you code.

When I use this code , the program ask me provide the pickle. But I don't know where can download it?

![image](https://user-images.githubusercontent.com/38171494/47981285-37fa3d00-e106-11e8-9648-97f62efe91a1.png)

**Comment by jppgks** [comment]
Hi @hackpython, you can find these datasets on FloydHub.

- [Text embeddings](https://www.floydhub.com/jppgks/datasets/stackgan-cub-text-embeddings)
- [Bird images](https://www.floydhub.com/jppgks/datasets/cub)
